### ISSUE TITLE
When using dependency_overrides, dependency is direct overridden which not considering

### ISSUE THREAD

**Issue by WilliamMaybe** [alexei-sintotski/pubspec_lock#33]
When using dependency_overrides, dependency is direct overridden which not considering

xxxxxxx:
    dependency: "direct overridden"
    description:
      path: "."
      ref: master
      resolved-ref: xxxxx
      url: "xxxxxxxxxx"
    source: git
    version: "0.0.1"

**Comment by alexei-sintotski** [comment]
@WilliamMaybe Thank you for reporting! This seems a new pub feature, I will check it out.

**Comment by alexei-sintotski** [comment]
@WilliamMaybe I cannot reproduce this issue with Dart 2.14.3. What Dart or Flutter version do you use?

**Comment by WilliamMaybe** [comment]
Flutter 2.2.3

**Comment by PoloLacoste** [comment]
I got the same error !

I have this in my `pubspec.yaml` file:

```yaml
dependency_overrides:
  analyzer: ^3.4.1
```

In my pubspec.lock file i have this:

```
analyzer:
 dependency: "direct overridden"
 description:
  name: analyzer
  url: "https://pub.dartlang.org"
 source: hosted
 version: "3.4.1"
```

I'm using the version `3.0.1` of `pubspec_lock`.
